//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBFORMSAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class newuserreg
    {
        public int Userid { get; set; }
        public string Username { get; set; }
        public string Pwd { get; set; }
        public string Repwd { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Maritalstatus { get; set; }
        public Nullable<System.DateTime> Joindate { get; set; }
    }
}
